name: food_delivery
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  otp_pin_field: ^1.2.0+2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.0
  google_maps_flutter: ^2.3.1
  custom_map_markers: ^0.0.2+1
  http: ^1.1.0
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.0
  intl: ^0.19.0
  flutter_native_timezone: ^2.0.0  # REPLACE flutter_timezone
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/font/Metropolis-Regular.otf
        - asset: assets/font/Metropolis-Medium.otf
          weight: 500
        - asset: assets/font/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/font/Metropolis-Bold.otf
          weight: 700
        - asset: assets/font/Metropolis-ExtraBold.otf
          weight: 800
